server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-request: true
      force-response: true
  tomcat:
    uri-encoding: UTF-8

spring:
  mvc:
    static-path-pattern: /static/**
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: "jdbc:mariadb://localhost:8001/papajohns?useUnicode=true&characterEncoding=UTF-08"
    username: "root"
    password: "toor"

mybatis:
  mapper-locations:
    - /mappers/*.xml
